repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]

      - id: rstcheck
        name: rstcheck
        stages: [commit]
        language: python
        types: [rst]
        entry: pipenv run rstcheck
      
      - id: update-cmdlist
        name: update-cmdlist
        stages: [commit]
        language: system
        entry: ./bin/update-commandlist.sh && git add docs/COMMANDS.rst
