#!/usr/bin/env python3

import random

import click


def get_data():
    return map(str.strip, open("data/sanalista5.txt", "r").readlines())


def output(data, limit, rand):
    data = list(data)
    if rand:
        random.shuffle(data)
    data = data[:limit]
    data.sort()

    return "\n".join(data)


@click.command()
@click.option("-l", "--limit", type=click.IntRange(min=1), default=10)
@click.option("-r", "--rand", help="Randomise values", is_flag=True)
def search(limit, rand):
    data = get_data()

    click.echo(output(data, limit, rand))


if __name__ == "__main__":
    search()
